---
apiVersion: v1
kind: Service
metadata:
  name: pet-service
  namespace: devops

  labels:
    app: pet-app
spec:
  selector:
    app: pet-app
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-deploy
  namespace: devops
  labels:
    app: pet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-app
  template:
    metadata:
      labels:
        app: pet-app
    spec:
      containers:
      - name: pet-container
        image: bds1959/spring-petclinic1:latest
        ports:
        - containerPort: 8080
